name: BlueMap - Render WupaServer

on:
  schedule:
    - cron: "0 16 * * 6" # UTC / UTC+8 每周日 00:00
  workflow_dispatch: {}

jobs:
  build:
    uses: EfinaServer/bluemap-action/.github/workflows/build-map.yml@main
    with:
      runs-on: blacksmith-2vcpu-ubuntu-2404
      server-directory: Wupa
      netlify-site-id: f2ac50f8-0315-4deb-ba4d-2ad173cf8097
    secrets:
      PTERODACTYL_PANEL_URL: ${{ secrets.PTERODACTYL_PANEL_URL }}
      PTERODACTYL_API_KEY: ${{ secrets.PTERODACTYL_API_KEY }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
